### ISSUE TITLE
Teams backup addition

### ISSUE THREAD

**Issue by Mewburn** [VeeamHub/martini-web#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
There is the option to backup Sharepoint, Exhange and Ondrive but we would like the ability to backup Microsoft Teams too.

**Describe alternatives you've considered**

**Additional context**

**Comment by nielsengelen** [comment]
Hi,

If you are talking about actually backing up Teams data; this is available in Veeam Backup for Microsoft Office 365 v5. Teams support has been added in the self-service portal (which is part of Project Martini) available via https://github.com/nielsengelen/vbo365-rest/. 

Currently, Project Martini provides no Teams support since the 'self-service part' code has changed a lot and needs to be implemented.
